### ISSUE TITLE
Problems whit validateArray

### ISSUE THREAD

**Issue by GoldraK** [gothinkster/slim-php-realworld-example-app#10]
I am using your development to make a new API.

But I have encountered a problem with validateArray and can not use the when option

I have the following data array:

```
$ values ​​["name"] = "second order";
$ values ​​["use_building"] = 8;
$ values ​​["other_use_building"] = "cave";
```

The validation has to check that when use_building is 8 the other_use_building is not empty.

If I perform the validation in a file for tests, the following validation works correctly:

```
$buildingValidator = v::key('use_building', v::optional(v::intVal()))
    ->when(v::key('use_building', v::equals(8)),
        v::key('other_use_building', v::notEmpty()),
        v::key('use_building', v::optional(v::intVal()))
    );

var_dump($buildingValidator->validate($values));
```

But when I enter it in the validateArray system

```
return $this->validator->validateArray($values,
            [
                'name' => v::notOptional()
                    ->notEmpty(),
                'use_building' => v::optional(
                    v::intVal()
                ),
                'other_use_building' =>
                    v::key('use_building', v::optional(v::intVal()))
                        ->when(v::key('use_building', v::equals(8)),
                            v::key('other_use_building', v::notEmpty()),
                            v::key('use_building', v::optional(v::intVal()))
                        )
            ]);
```

tells me what error when he had to see given true

```object(Coda\Validation\Validator)#131 (1) {
  ["errors":protected]=>
  array(1) {
    ["other_use_building"]=>
    array(2) {
      [0]=>
      string(32) "Key use_building must be present"
      [1]=>
      string(32) "Key use_building must be present"
    }
  }
}```

Thanks for the help

**Comment by alhoqbani** [comment]
I'm not an expert in the Respect\Validation library, but I think to have conditional rules based on another field's, we must pass the complete data to validate.

 The [validateArray](https://github.com/gothinkster/slim-php-realworld-example-app/blob/47759d4d49f43b8747fedc36579a5123f9950ca6/src/Conduit/Validation/Validator.php#L46-L59) method passes a single value for each rule, unlike your example where you pass the whole `$values` array. So, when we validate the field `other_use_building` we pass only the value for this field. Hence, the error `Key use_building must be present`. 

Try replacing [this line](https://github.com/gothinkster/slim-php-realworld-example-app/blob/47759d4d49f43b8747fedc36579a5123f9950ca6/src/Conduit/Validation/Validator.php#L51) 
```php
$rule->setName($field)->assert($this->getValue($values, $field));
```
with 
```php
$rule->setName($field)->assert($values);
```
I haven't tested this change, it might work or you may need to define your logic for you specific use case.

**Comment by GoldraK** [comment]
Thanks, go to see
