### ISSUE TITLE
sort by date

### ISSUE THREAD

**Issue by X-Anonymous-Y** [gothinkster/slim-php-realworld-example-app#12]
How can I sort the comments by date? that the newest will be shown first?

i use slim as backend and vue as fontend

Thanks

**Comment by alhoqbani** [comment]
We use [Laravel Eloquent](https://laravel.com/docs/5.7/eloquent) in this project. If you're using the same, you can use [`orderBy/latest`](https://laravel.com/docs/5.7/queries#ordering-grouping-limit-and-offset) to sort the comments.
