### ISSUE TITLE
Validator issue 

### ISSUE THREAD

**Issue by vitalijalbu** [gothinkster/slim-php-realworld-example-app#14]
When trying to register or login, it shows me validation error:

[https://drive.google.com/file/d/1s5VHPAstmfY5bYnoJiGLm_aYuhVo1D8N/view?usp=sharing](url)

**Comment by alhoqbani** [comment]
I can’t open the link.

**Comment by vitalijalbu** [comment]
Just copy and paste😉👍

Il mer 13 feb 2019, 20:09 Hamoud <notifications@github.com> ha scritto:

**Comment by alhoqbani** [comment]
Make sure to add request header: `Content-Type: application/json`
