### ISSUE TITLE
error on Readme.

### ISSUE THREAD

**Issue by horaciod** [gothinkster/slim-php-realworld-example-app#5]
in *Data Seeding*
say  "php vendor/bin/phinx migrate" but is not working 
but "php vendor/bin/phinx seed:run" works

**Comment by alhoqbani** [comment]
Yes, the readme is missing the second step. 

You need to run both commands to seed the database. 

To create the database schema:
```bash
php vendor/bin/phinx migrate
```
And to populate the data:
```bash
php vendor/bin/phinx seed:run
```

Also, as mentioned in the readme, you can use the command `composer refresh-database` to rollback all migrations, migrate the database and seed the data.
