### ISSUE TITLE
db unused on LoginController

### ISSUE THREAD

**Issue by cgomezmendez** [gothinkster/slim-php-realworld-example-app#9]
https://github.com/gothinkster/slim-php-realworld-example-app/blob/47759d4d49f43b8747fedc36579a5123f9950ca6/src/Conduit/Controllers/Auth/LoginController.php#L19

We are getting the db in logincontroller but db logic is done in Auth Service so there is not much point in importing it here.

**Comment by alhoqbani** [comment]
Yes, you are right. It is not used in the LoginController.
